---
# tasks file for openvino

- name: Check that the OS is Debian based system
  ansible.builtin.fail:
    msg: "This playbook currently supports only Debian based system"
  when: ansible_os_family != "Debian"

- ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == "Debian"
